language: node_js

node_js:
- "14"

install:
- "npm ci --no-optional"

script:
- "npm run build -- --prod --base-href $BASE_HREF"

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  project_name: tanktread
  skip-cleanup: true
  keep_history: true
  on:
    branch: master
  target_branch: gh-pages
  local_dir: dist/tanktread

env:
  global:
    - BASE_HREF="https://maymoonsley.github.io/tanktread/"
